package com.mobius.software.telco.protocols.gtp.api.headers.v2;
/*Mobius Software LTD
Copyright 2019, Mobius Software LTD and individual contributors
by the @authors tag.

This program is free software: you can redistribute it and/or modify
under the terms of the GNU Affero General Public License as
published by the Free Software Foundation; either version 3 of
the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>*/
import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.XmlEnum;

@XmlEnum(String.class)
public enum CauseType 
{	
	LOCAL_DETACH(2),COMPLETE_DETACH(3),RAT_CHANGED_FROM_3GPP_TO_NON_3GPP(4),
	ISR_DEACTIVATION(5),ERROR_INDICATION_RECEIVED_FROM_RNC(6),IMSI_DETACH_ONLY(7),REACTIVATION_REQUESTED(8),PDN_RECONNECTION_TO_THIS_APN_DISALLOWED(9),
	ACCESS_CHANGED_FROM_3GPP_TO_NON_3GPP(10),PDN_CONNECTION_INACTIVITY_TIMER_EXPIRES(11),PGW_NOT_RESPONDING(12),NETWORK_FAILURE(13),
	QOS_PARAMETER_MISMATCH(14),REQUEST_ACCEPTED(16),REQUEST_ACCEPTED_PARTIALLY(17),NEW_PDN_DUE_TO_NETWORK_PREFERENCE(18),
	NEW_PDN_DUE_TO_SINGLE_ADDRESS_BEARER_ONLY(19),CONTEXT_NOT_FOUND(64),INVALID_MESSAGE_FORMAT(65),VERSION_NOT_SUPPORTED_BY_NEXT_PEER(66),
	INVALID_LENGTH(67),SERVICE_NOT_SUPPORTED(68),MANDATORY_IE_INCORRECT(69),MANDATORY_IE_MISSING(70),SYSTEM_FAILURE(72),
	NO_RESOURCE_AVAILABLE(73),SEMANTIC_ERROR_IN_TFT_INFORMATION(74),SYNTATIC_ERROR_IN_TFT_INFORMATION(75),
	SEMANTIC_ERROR_IN_PACKET_FILTERS(76),SYNTATIC_ERROR_IN_PACKET_FILTERS(77),MISSING_OR_UNKNOWN_APN(78),
	GRE_KEY_NOT_FOUND(80),REALLOCATION_FAILURE(81),DENIED_IN_RAT(82),PREFERRED_PDN_NOT_SUPPORTED(83),ALL_DYNAMIC_ADDRESSES_ARE_OCCUPIED(84),
	UE_CONTEXT_WITHOUT_TFT_ALREADY_ACTIVATED(85),PROTOCOL_TYPE_NOT_SUPPORTED(86),UE_NOT_RESPONDING(87),UE_REFUSES(88),SERVICE_DENIED(89),
	UNABLE_TO_PAGE_UE(90),NO_MEMORY_AVAILABLE(91),USER_AUTHENTICATION_FAILED(92),APN_ACCESS_DENIED_NO_SUBSCRIPTION(93),REQUEST_REJECTED(94),
	PTMSI_SIGNATURE_MISMATCH(95),IMSI_IMEI_UNKNOWN(96),SEMANTIC_ERROR_IN_TAD_OPERATION(97),SYNTATIC_ERROR_IN_TAD_OPERATION(98),
	REMOTE_PEER_NOT_RESPONDING(100),COLLISION_WITH_NETWORK_INITIATED_REQUEST(101),UNABLE_TO_PAGE_UE_DUE_TO_SUSPENSION(102),
	CONDITIONAL_IE_MISSING(103),APN_RESTRICTION_INCOMPATIBLE_WITH_CURRENTLY_ACTIVE_PDN_CONNECTION(104),INVALID_OVERALL_LENGTH(105),
	DATA_FORWARDING_NOT_SUPPORTED(106),INVALID_REPLY_FROM_REMOTE_PEER(107),FALLBACK_TO_GTPV1(108),INVALID_PEER(109),
	TEMPORARY_REJECT_DUE_TO_HANDOVER_TAU_RAU_PROCEDURE_IN_PROGRESS(110),MODIFICATION_NOT_LIMITED_TO_S1_U_BEARERS(111),
	REQUEST_REJECTED_FOR_PMIPV6_REASON(112),APN_CONGESTION(113),BEARER_HANDLING_NOT_SUPPORTED(114),UE_ALREADY_REATTACHED(115),
	MULTIPLE_PDN_CONNECTIONS_FOR_A_GIVEN_APN_NOT_ALLOWED(116),TARGET_ADDRESS_RESTRICTED_FOR_THE_SUBSCRIBER(117),
	MME_SGSN_REFUSES_DUE_TO_VPLMN_POLICY(119),GTP_C_ENTITY_CONGESTION(120),LATE_OVERLAPPING_REQUEST(121),TIMEOUT_REQUEST(122),
	UE_TEMPORARY_NOT_REACHABLE_DUE_TO_POWER_SAVING(123),REALLOCATION_FAILURE_DUE_TO_NAS_MESSAGE_REDIRECTION(124),
	UE_NOT_AUTHORIZED_BY_OCS_OR_EXTERNAL_AAA_SERVER(125),MULTIPLE_ACCESSES_TO_PDN_CONNECTION_NOT_ALLOWED(126),
	REQUEST_REJECTED_DUE_TO_UE_CAPABILITY(127),UNKNOWN(-1);

	private static final Map<Integer, CauseType> intToTypeMap = new HashMap<Integer, CauseType>();
	static 
	{
	    for (CauseType type : CauseType.values()) 
	    {
	        intToTypeMap.put(type.value, type);
	    }
	}

	public static CauseType fromInt(int i) 
	{
		CauseType type = intToTypeMap.get(Integer.valueOf(i));
	    if (type == null) 
	        return CauseType.UNKNOWN;
	    
	    return type;
	}
	
	private int value;
	
	private CauseType(int value)
	{
		this.value=value;
	}
	
	public int getValue()
	{
		return value;
	}
}
