package com.mobius.software.telco.protocols.gtp.api.headers.v2;
/*Mobius Software LTD
Copyright 2019, Mobius Software LTD and individual contributors
by the @authors tag.

This program is free software: you can redistribute it and/or modify
under the terms of the GNU Affero General Public License as
published by the Free Software Foundation; either version 3 of
the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>*/
import java.util.HashMap;
import java.util.Map;

public enum GTP2MessageType 
{
	ECHO_REQUEST(1),ECHO_RESPONSE(2),VERSION_NOT_SUPPORTED(3),DIRECT_TRANSFER_REQUEST(4),DIRECT_TRANSFER_RESPOSE(5),
	NOTIFICATION_REQUEST(6),NOTIFICATION_RESPONSE(7),RIM_INFORMATION_TRANSFER(17),SRVCC_PS_TO_CS_REQUEST(25),
	SRVCC_PS_TO_CS_RESPONSE(26),SRVCC_PS_TO_CS_COMPLETE_NOTIFICATION(27),SRVCC_PS_TO_CS_COMPLETE_ACKNOWLEDGE(28),
	SRVCC_PS_TO_CS_CANCEL_NOTIFICATION(29),SRVCC_PS_TO_CS_CANCEL_ACKNOWLEDGE(30),SRVCC_CS_TO_PS_REQUEST(31),
	CREATE_SESSION_REQUEST(32),CREATE_SESSION_RESPONSE(33),MODIFY_BEARER_REQUEST(34),MODIFY_BEARER_RESPONSE(35),
	DELETE_SESSION_REQUEST(36),DELETE_SESSION_RESPONSE(37),CHANGE_NOTIFICATION_REQUEST(38),CHANGE_NOTIFICATION_RESPONSE(39),
	REMOTE_UE_REPORT_NOTIFICATION(40),REMOTE_UE_REPORT_ACKNOWLEDGE(41),MODIFY_BEARER_COMMAND(64),MODIFY_BEARER_FAILURE_INDICATION(65),
	DELETE_BEARER_COMMAND(66),DELETE_BEARER_FAILURE_INDICATION(67),BEARER_RESOURCE_COMMAND(68),BEARER_RESOURCE_FAILURE_INDICATION(69),
	DOWNLINK_DATA_FAILURE_INDICATION(70),TRACE_SESSION_ACTIVATION(71),TRACE_SESSION_DEACTIVATION(72),STOP_PAGING_INDICATION(73),
	CREATE_BEARER_REQUEST(95),CREATE_BEARER_RESPONSE(96),UPDATE_BEARER_REQUEST(97),UPDDATE_BEARER_RESPONSE(98),DELETE_BEARER_REQUEST(99),
	DELETE_BEARER_RESPONSE(100),DELETE_PDN_CONNECTION_SET_REQUEST(101),DELETE_PDN_CONNECTION_SET_RESPONSE(102),PGW_DOWNLINK_TRIGGERING_INDICATION(103),
	PGW_DOWNLINK_TRIGGERING_ACKNOWLEDGE(104),IDENTIFICATION_REQUEST(128),IDENTIFICATION_RESPONSE(129),CONTEXT_REQUEST(130),
	CONTEXT_RESPONSE(131),CONTEXT_ACKNOWLEDGE(132),FORWARD_RELOCATION_REQUEST(133),FORWARD_RELOCATION_RESPONSE(134),
	FORWARD_RELOCATION_COMPLETE_NOTIFICATION(135),FORWARD_RELOCATION_COMPLETE_ACKNOWLEDGE(136),FORWARD_ACCESS_CONTEXT_NOTIFICATION(137),
	FORWARD_ACCESS_CONTEXT_ACKNOWLEDGE(138),RELOCATION_CANCEL_REQUEST(139),RELOCATION_CANCEL_RESPONSE(140),CONFIGURATION_TRANSFER_TUNNEL(141),
	DETACH_NOTIFICATION(149),DETACH_ACKNOWLEDGE(150),CS_PAGING_INDICATION(151),RAN_INFORMATION_RELAY(152),ALERT_MME_NOTIFICATION(153),
	ALERT_MME_ACKNOWLEDGE(154),UE_ACTIVITY_NOTIFICATION(155),UE_ACTIVITY_ACKNOWLEDGE(156),ISR_STATUS_INDICATION(157),
	UE_REGISTRATION_QUERY_REQUEST(158),UE_REGISTRATION_QUERY_RESPONSE(159),CREATE_FORWARDING_TUNNEL_REQUEST(160),
	CREATE_FORWARDING_TUNNEL_RESPONSE(161),SUSPEND_NOTIFICATION(162),SUSPEND_ACKNOWLEDGE(163),RESUME_NOTIFICATION(164),
	RESUME_ACKNOWLEDGE(165),CREATE_INDIRECT_DATA_FORWARDING_TUNNEL_REQUEST(166),CREATE_INDIRECT_DATA_FORWARDING_TUNNEL_RESPONSE(167),
	DELETE_INDIRECT_DATA_FORWARDING_TUNNEL_REQUEST(168),DELETE_INDIRECT_DATA_FORWARDING_TUNNEL_RESPONSE(169),
	RELEASE_ACCESS_BEARER_REQUEST(170),RELEASE_ACCESS_BEARER_RESPONSE(171),DOWNLINK_DATA_NOTIFICATION(176),
	DOWNLINK_DATA_NOTIFICATION_ACKNOWLEDGE(177),PGW_RESTART_NOTIFICATION(179),PGW_RESTART_NOTIFICATION_ACKNOWLEDGE(180),
	UPDATE_PDN_CONNECTION_SET_REQUEST(200),UPDATE_PDN_CONNECTION_SET_RESPONSE(201),MODIFY_ACCESS_BEARER_REQUEST(211),
	MODIFY_ACCESS_BEARER_RESPONSE(212),MBMS_SESSION_START_REQUEST(231),MBMS_SESSION_START_RESPONSE(232),
	MBMS_SESSION_UPDATE_REQUEST(233),MBMS_SESSION_UPDATE_RESPONSE(234),MBMS_SESSION_STOP_REQUEST(235),MBMS_SESSION_STOP_RESPONSE(236),
	SRVCC_CS_TO_PS_RESPONSE(240),SRVCC_CS_TO_PS_COMPLETE_NOTIFICATION(241),SRVCC_CS_TO_PS_COMPLETE_ACKNOWLEDGE(242),
	SRVCC_CS_TO_PS_CANCEL_NOTIFICATION(243),SRVCC_CS_TO_PS_CANCEL_ACKNOWLEDGE(244),UNKNOWN(0);

	private static final Map<Integer, GTP2MessageType> intToTypeMap = new HashMap<Integer, GTP2MessageType>();
	static
	{
	    for (GTP2MessageType type : GTP2MessageType.values()) 
	    {
	        intToTypeMap.put(type.value, type);
	    }
	}

	public static GTP2MessageType fromInt(int i) 
	{
		GTP2MessageType type = intToTypeMap.get(Integer.valueOf(i));
	    if (type == null) 
	        return GTP2MessageType.UNKNOWN;
	    
	    return type;
	}
	
	int value;
	
	private GTP2MessageType(int value)
	{
		this.value=value;
	}
	
	public int getValue()
	{
		return value;
	}
}
