package com.mobius.software.telco.protocols.gtp.api.headers.v2;
/*Mobius Software LTD
Copyright 2019, Mobius Software LTD and individual contributors
by the @authors tag.

This program is free software: you can redistribute it and/or modify
under the terms of the GNU Affero General Public License as
published by the Free Software Foundation; either version 3 of
the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>*/
import java.util.HashMap;
import java.util.Map;

public enum GTP2ElementType 
{
	UNKNOWN(0),IMSI(1),CAUSE(2),RECOVERY(3),HRPD_SECTOR_ID(4),S101_TRANSPARENT_CONTAINER(5),HANDOVER_INDICATOR(6),PDN_GW_PMIP_GRE_TUNNEL_INFO(7),
	S103_GRE_TUNNEL_INFO(8),S103_HSGW_IP_ADDRESS(9),SESSION_ID_2(11),UNATHENTICATION_IMSI(12),EUTRAN_ROUND_TRIP_DELAY(13),S_121_TRANSPARENT_CONTAINER(35),
	RIM_ROUTING_ADDRESS(36),STN_SR(51),SOURCE_TO_TARGET_TRANSPARENT_CONTAINER(52),TARGET_TO_SOURCE_TRANSPARENT_CONTAINER(53),MM_CONTEXT_FOR_EUTRAN(54),
	MM_CONTEXT_FOR_UTRAN(55),SRVCC_CAUSE(56),TARGET_RNC_ID(57),TARGET_GLOBAL_CELL_ID(58),TEID_C(59),SV_FLAGS(60),SAI(61),MM_CONTEXT_FOR_CS_TO_PS(62),
	APN(71),AMBR(72),EPS_BEARER_ID(73),IP_ADDRESS(74),MEI(75),MSISDN(76),INDICATION(77),PROTOCOL_CONFIGURATION_OPTIONS(78),PDN_ADDRESS_ALLOCATION(79),
	BEARER_QOS(80),FLOW_QOS(81),RAT_TYPE(82),SERVING_NETWORK(83),BEARER_TFT(84),TRAFFIC_AGGREGATION_DESCRIPTION(85),USER_LOCATION_INFORMATION(86),
	FTEID(87),TMSI(88),GLOBAL_CN_ID(89),S103_PDN_DATA_FORWARDING_INFO(90),S1_U_PDN_DATA_FORWARDING_INFO(91),DELAY_VALUE(92),BEARER_CONTEXT(93),
	CHARGING_ID(94),CHARGING_CHARACTERISTICS(95),TRACE_INFORMATION(96),BEARER_FLAGS(97),PDN_TYPE(99),PROCEDURE_TRANSACTION_ID(100),
	MM_CONTEXT_GSM_AND_TRIPLETS(103),MM_CONTEXT_UMTS_CIPHER_AND_QUINTIPLETS(104),MM_CONTEXT_GSM_CIPHER_AND_QUINTIPLETS(105),MM_CONTEXT_UMTS_AND_QUINTIPLETS(106),
	MM_CONTEXT_EPS(107),MM_CONTEXT_UMTS_KEY_QUADRIPLETS_AND_QUINTIPLETS(108),PDN_CONNECTION(109),PDU_NUMBERS(110),PTMSI(111),PTMSI_SIGNATURE(112),
	HOP_COUNTER(113),UE_TIMEZONE(114),TRACE_REFERENCE(115),COMPLETE_REQUEST_MESSAGE(116),GUTI(117),FCONTAINER(118),FCAUSE(119),PLMN_ID(120),
	TARGET_IDENTIFICATION(121),PACKET_FLOW_ID(123),RAB_CONTEXT(124),SOURCE_RNC_PDCP_CONTEXT_INFO(125),PORT_NUMBER(126),APN_RESTRICTION(127),
	SELECTION_MODE(128),SOURCE_IDENTIFICATION(129),CHANGE_REPORTING_ACTION(131),FQ_CSID(132),CHANNEL_NEEDED(133),EMLPP_PRIORITY(134),
	NODE_TYPE(135),FQDN(136),TRANSACTION_IDENTIFIER(137),MBMS_SESSION_DURATION(138),MBMS_SERVICE_AREA(139),MBMS_SESSION_IDENTIFIER(140),
	MBMS_FLOW_IDENTIFIER(141),MBMS_IP_MULTICAST_DISTRIBUTION(142),MBMS_DISTRIBUTION_ACKNOWLEDGMENT(143),RFSP_INDEX(144),USER_CSG_INFORMATION(145),
	CSG_INFORMATION_REPORTING_ACTION(146),CSG_ID(147),CSG_MEMBERSHIP_INDICATION(148),SERVICE_INDICATOR(149),DETACH_TYPE(150),LDN(151),
	NODE_FEATURES(152),MBMS_TIME_TO_DATA_TRANSFER(153),THROTTLING(154),ALLOCATION_RETENTION_PRIORITY(155),EPC_TIMER(156),SIGNALING_PRIORITY_INDICATOR(157),
	TMGI(158),ADDITIONAL_MM_CONTEXT_FOR_SRVCC(159),ADDITIONAL_FLAGS_FOR_SRVCC(160),MDT_CONFIGURATION(162),ADDITIONAL_PROTOCOL_CONFIGURATION_OPTIONS(163),
	ABSOLUTE_TIME_OF_MBMS_DATA_TRANSFER(164),HENB_INFORMATION_REPORTING(165),IPV4_CONFIGURATION_PARAMETERS(166),CHANGE_TO_REPORT_FLAGS(167),
	ACTION_INDICATOR(168),TWAN_IDENTIFIER(169),ULI_TIMESTAMP(170),MBMS_FLAGS(171),RAN_NAS_CAUSE(172),CN_OPERATOR_SELECTION_ENTITY(173),
	TRUSTED_WLAN_MODE_INDICATION(174),NODE_NUMBER(175),NODE_IDENTIFIER(176),PRESENCE_REPORTING_AREA_ACTION(177),PRESENCE_REPORTING_AREA_INFORMATION(178),
	TWAN_IDENTIFIER_TIMESTAMP(179),OVERLOAD_CONTROL_INFORMATION(180),LOAD_CONTROL_INFORMATION(181),METRIC(182),SEQUENCE_NUMBER(183),
	APN_AND_RELATIVE_CAPACITY(184),WLAN_OFFLOADABILITY_INDICATION(185),PAGING_AND_SERVICE_INFORMATION(186),INTEGER_NUMBER(187),
	MILLISECONDS_TIMESTAMP(188),MONITORING_EVENT_INFORMATION(189),ECGI_LIST(190),REMOTE_UE_CONTEXT(191),REMOTE_USER_ID(192),REMOTE_UE_IP_INFORMATION(193),
	CIOT_OPTIMIZATION_SUPPORT_INDICATION(194),SCEF_PDN_CONNECTION(195),HEADER_COMPRESSION_CONFIGURATION(196),EXTENDED_PROTOCOL_CONFIGURATION_OPTIONS(197),
	SERVING_PLMN_RATE_CONTROL(198),COUNTER(199),MAPPED_UE_USAGE_TYPE(200),SECONDARY_RAT_DATA_USAGE_REPORT(201),UP_FUNCTION_SELECTION_INDICATION_FLAGS(202),
	MAXIMUM_PACKET_LOSS_RATE(203),EXTENTION(254),PRIVATE_EXTENTION(255);
	
	private static final Map<Integer, GTP2ElementType> intToTypeMap = new HashMap<Integer, GTP2ElementType>();
	static
	{
	    for (GTP2ElementType type : GTP2ElementType.values()) 
	    {
	        intToTypeMap.put(type.value, type);
	    }
	}

	public static GTP2ElementType fromInt(int i) 
	{
		GTP2ElementType type = intToTypeMap.get(Integer.valueOf(i));
	    if (type == null) 
	        return GTP2ElementType.UNKNOWN;
	    
	    return type;
	}
	
	int value;
	
	private GTP2ElementType(int value)
	{
		this.value=value;
	}
	
	public int getValue()
	{
		return value;
	}
}
