package com.mobius.software.telco.protocols.gtp.api.headers;
/*Mobius Software LTD
Copyright 2019, Mobius Software LTD and individual contributors
by the @authors tag.

This program is free software: you can redistribute it and/or modify
under the terms of the GNU Affero General Public License as
published by the Free Software Foundation; either version 3 of
the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>*/
import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.XmlEnum;

@XmlEnum(String.class)
public enum RanapCauseType 
{	
	RAB_PREEMPTED(1),TRELOCOVERALL_EXPIRY(2),TERLOPCREP_EXPIRY(3),TRELOCOMPLETE_EXPIRY(4),
	TQUEING_EXPIRY(5),RELOCATION_TRIGGERED(6),UNABLE_TO_ESTABLISH_DURING_RELOCATION(8),UNKNOWN_TARGET_RNC(9),
	RELOCATION_CANCELLED(10),SUCCESFULL_RELOCATION(11),REQUESTING_CIPHERING_OR_INTEGRITY_PROTECTION_ALGO_NOT_SUPPORTED(12),
	CHANGE_OF_CIPHERING_OR_INTEGRITY_PROTECTION_ALGO_NOT_SUPPORTED(13),FAILURE_IN_RADIO_INTERFACE_PROCEDURE(14),
	RELEASE_DUE_TO_UTRAN_GENERATED_REASON(15),USER_INACTIVITY(16),TIME_CRITICAL_RELLOCATION(17),REQUESTED_TRAFFIC_CLASS_NOT_AVAILABLE(18),
	INVALID_RAB_PARAMETER_VALUE(19),REQUESTED_MAX_BIT_RATE_NOT_AVAILABLE(20),REQUESTED_MAX_BIT_RATE_DL_NOT_AVAILABLE(33),
	REQUESTED_MAX_BIT_RATE_UL_NOT_AVAILABLE(34),REQUESTED_GUARANTEED_BIT_RATE_NOT_AVAILABLE(21),REQUESTED_GUARANTEED_BIT_RATE_DL_NOT_AVAILABLE(35),
	REQUESTED_GUARANTEED_BIT_RATE_UL_NOT_AVAILABLE(36),REQUESTED_TRANSFER_DELAY_NOT_ACHIEVABLE(22),INVALID_RAB_PARAMETERS_COMBINATION(23),
	CONDITION_VIOLATION_FOR_SDU_PARAMETERS(24),CONDITION_VIOLATION_FOR_TRAFFIC_HANDLING_PRIORITY(25),CONDITION_VIOLATION_FOR_GUARANTEED_BITRATE(26),
	USER_PLANE_VERSIONS_NOT_SUPPORTED(27),LU_UP_FAILURE(28),TERLOCALLOC_EXPIRY(7),RELOCATION_FAILURE_IN_TARGET_CN_RNC_OR_TARGET_SYSTEM(29),
	INVALID_RAB_ID(30),NO_REMAINING_RAB(31),INTERACTION_WITH_OTHER_PROCEDURES(32),REPEATED_INTEGRITY_CHECK_FAILURE(37),
	REQUESTED_REPORT_TYPE_NOT_SUPPORTED(38),REQUEST_SUPERSEEDED(39),RELEASE_DUE_TO_UE_GENERATED_SIGNALLING_CONNECTION_RELEASE(40),
	RESOURCE_OPTIMIZATION_ALLOCATION(41),REQUESTED_INFORMATION_NOT_AVAILABLE(42),RELOCATION_DESIRABLE_FOR_RADIO_REASONS(43),
	RELLOCATION_NOT_SUPPORTED_IN_TARGET_RNC_OR_TARGET_SYSTEMS(44), DIRECTED_RETRY(45),RADIO_CONNECTION_WITH_UE_LOST(46),
	RNC_UNABLE_TO_ESTABLISH_ALL_RFCS(47),DECIPHERING_KEY_NOT_AVAILABLE(48),DEDICATED_ASSISTANCE_DATA_NOT_AVAILABLE(49),
	RELOCATION_TARGET_NOT_ALLOWED(50),LOCATION_REPORTING_CONGESTION(51),REDUCE_LOAD_IN_SERVICE_CELL(52),NO_RADIO_RESOURCES_AVAILABLE_IN_TARGET_CELL(53),
	GERAN_LU_MODE_FAILURE(54),ACCESS_RESTRICTED_DUE_TO_SHARED_NETWORK(55),INCOMING_RELOCATION_NOT_SUPPORTED_DUE_TO_PUESBINE_FEATURE(56),
	TRAFFIC_LOAD_IN_TARGET_CELL_HIGHER_THEN_IN_SOURCE_CELL(57),MBMS_NO_MULTICAST_SERVICE_FOR_THIS_UE(58),MBMS_UNKNOWN_UE_ID(59),
	SUCCESFULL_MBMS_SESSION_START_NO_DATA_BEARER_NECESSARY(60),MBMS_SUPRESSED_DUE_TO_NNSF(61),MBMS_UE_LINKING_ALREADY_DONE(62),
	MBMS_UE_DELINKING_FAILURE_NO_EXISTING_UE_LINKING(63),TMGI_UNKNOWN(64),
	SIGNALING_TRANSPORT_REPORT_FAILURE(65),LU_TRANSPORT_CONNECTION_FAILED_TO_ESTABLISH(66),USER_RESTRICTION_START_INDICATION(81),
	USER_RESTRICTION_END_INDICATION(82),NORMAL_RELEASE(83),CSG_SUBSCRIPTION_EXPIRED(84),TRANSFER_SYNTAX_ERROR(97),SEMANTIC_ERROR(98),
	MESSAGE_NOT_COMPATIBLE_WITH_RECEIVER_STATE(99),ABSTRACT_SYNTAX_ERROR_REJECT(100),ABSTRACT_SYNTAX_ERROR_IGNORE_OR_NOTIFY(101),
	ABSTRACT_SYNTAX_ERROR_FALSLY_CONSTRUCTED_MESSAGE(102),OM_INTERVENTION(113),NO_RESOURCE_AVAILABLE(114),UNSPECIFIED_FAILURE(115),
	NETWORK_OPTIMIZATION(116),IP_MULTICAST_ADDRESS_AND_APN_NOT_AVAILABLE(257),MBMS_DEREGISTRATION_REJECTED_DUE_TO_IMPLICIT_REGISTRATION(258),
	MBMS_REQUEST_SUPERSEEDED(259),MBMS_DEREGISTRATION_DURING_SESSION_NOT_ALLOWED(260),MBMS_NO_DATA_BEARER_NECESSARY(261),
	PERIODIC_LOCATION_INFORMATION_NOT_AVAILABLE(262),GTP_RESOURECE_UNAVAILABLE(263),TMGI_IN_USE_AND_OVERLAPPING_MBMS_SERVICE_AREA(264),
	MBMS_NO_CELL_IN_MBMS_SERVICE_AREA(265),NO_CS_LU_UP_RELOCATION(266),SUCCESFULL_MBMS_SESSION_START_IP_MULTICAST_BEARER_ESTABLISHED(267),
	CS_FALLBACK_TRIGGERED(268),INVALID_CSG_ID(269),UNKNOWN(-1);

	private static final Map<Integer, RanapCauseType> intToTypeMap = new HashMap<Integer, RanapCauseType>();
	static 
	{
	    for (RanapCauseType type : RanapCauseType.values()) 
	    {
	        intToTypeMap.put(type.value, type);
	    }
	}

	public static RanapCauseType fromInt(int i) 
	{
		RanapCauseType type = intToTypeMap.get(Integer.valueOf(i));
	    if (type == null) 
	        return RanapCauseType.UNKNOWN;
	    
	    return type;
	}
	
	private int value;
	
	private RanapCauseType(int value)
	{
		this.value=value;
	}
	
	public int getValue()
	{
		return value;
	}
}
